
package sss;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static org.eclipse.persistence.jpa.rs.util.JPARSLogger.exception;

/**
 *
 * @author Akshay
 */
public class employeemain extends javax.swing.JFrame {

    /**
     * Creates new form employeemain
     */
    public employeemain() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textArea1 = new java.awt.TextArea();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("EMPLOYEE  REGISTRATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 340, 26));

        jLabel2.setText("FIRST NAME :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 118, -1));

        jLabel3.setText("MID NAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, -1));

        jLabel4.setText("LAST NAME :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, -1));

        jLabel5.setText("CORRESPONDING ADD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, -1));

        jLabel6.setText("MOBILE NO.:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, 20));

        jLabel7.setText("EMAIL ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 65, -1));

        jLabel8.setText("APPLIATION ID :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 90, -1));
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 170, -1));
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 170, -1));
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, -1));
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 260, 120));
        getContentPane().add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 170, -1));
        getContentPane().add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 260, -1));
        getContentPane().add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 260, -1));

        button1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        button1.setLabel("REGISTER");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 240, -1));

        button2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        button2.setLabel("HOME");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
//<editor-fold defaultstate="collapsed" desc="comment">
{
    try {
        thequery("insert into employeeregister(firstname,midname,lastname,correspondingaddress,mobilenumber,emailid) values('"+textField1.getText()+"','"+textField2.getText()+"','"+textField3.getText()+"','"+textArea1.getText()+"','"+textField4.getText()+"','"+textField5.getText()+"')");
    }
 
    catch(Exception ex)
    {
    JOptionPane.showMessageDialog(rootPane,ex.getMessage());
    }
}




        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed



    
    
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
NewJFrame m=new NewJFrame();
                 m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

try{
    
    thequery("update  employeeregister set firstname='"+textField1.getText()+"',midname='"+textField2.getText()+"',lastname='"+textField3.getText()+"',correspondingaddress='"+textArea1.getText()+"',mobil"
            + "enumber='"+textField4.getText()+"',emailid='"+textField5.getText()+"' where firstname='"+textField1.getText()+"' ");
}catch (Exception ex)
{
    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

try{
    thequery("delete from employeeregister where firstname='"+textField1.getText()+"'");
}
    catch(Exception ex)    // TODO add your handling code here:
    {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    
   
 public void thequery(String query)throws SQLException
 {
     Connection con=null;
     Statement st=null;
     String url="jdbc:mysql://localhost:3306/salonbean";
     String userName="root";
     String password="9226794263";
     try
     {
         con=DriverManager.getConnection(url, userName, password);
         st=con.createStatement();
         st.executeUpdate(query);
         JOptionPane.showMessageDialog(null," REGISTRATION COMPLETED ");
     }
     catch(Exception ex)
             {
                 JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     
     
 
 }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeemain().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
